name: portfolio-react-ecommerce-container
services:
  postgre:
    image: estebanfmartinez/portfolio-postgre:latest
    container_name: portfolio-db
    environment:
      - POSTGRES_DB=portfoliodb
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=SomePassword#1
    ports:
      - "5432:5432"
    volumes:
      - porfolio_db_data:/var/lib/postgresql/data

  webapi:
    container_name: portfolio-web-api
    image: estebanfmartinez/portfolio-webapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - postgre
    ports:
      - "5000:5000"

  react-ecommerce:
    container_name: portfolio-react-ecommerce
    image: estebanfmartinez/portfolio-react-ecommerce:latest
    depends_on:
      - webapi
    ports:
      - "3000:3000"

volumes:
  porfolio_db_data: